import { AlignmentParams, Sequence, AlignmentResult } from '@/types/alignment';
import { 
  performClustalAlignment, 
  performMuscleAlignment, 
  performMafftAlignment,
  generateConsensusSequence,
  generateNewickTree
} from '@/utils/biowasm-msa';

/**
 * Performs a multiple sequence alignment based on the provided parameters
 * using Biowasm-powered tools
 * 
 * @param sequences Array of sequences to align
 * @param params Alignment parameters
 * @returns Promise resolving to alignment results
 */
export const performAlignment = async (
  sequences: Sequence[],
  params: AlignmentParams
): Promise<AlignmentResult> => {
  // Validate input
  if (sequences.length < 2) {
    throw new Error('At least two sequences are required for alignment');
  }

  let alignedSequences: Sequence[] = [];
  
  // Perform alignment based on selected method
  try {
    switch (params.method) {
      case 'clustal':
        alignedSequences = await performClustalAlignment(sequences, params);
        break;
      case 'muscle':
        alignedSequences = await performMuscleAlignment(sequences, params);
        break;
      case 'mafft':
        alignedSequences = await performMafftAlignment(sequences, params);
        break;
      default:
        throw new Error(`Unsupported alignment method: ${params.method}`);
    }
  } catch (error) {
    console.error(`Alignment failed: ${error}`);
    throw new Error(`Alignment failed: ${error instanceof Error ? error.message : String(error)}`);
  }
  
  // Generate consensus sequence
  const consensusSequence = generateConsensusSequence(alignedSequences);
  
  // Generate Newick tree
  const newickTree = await generateNewickTree(alignedSequences);
  
  // Return complete result
  return {
    alignedSequences,
    consensusSequence,
    newickTree,
    treeImage: null, // Will be generated by MSAViewer/PhylocanvasJS
    alignmentScore: calculateAlignmentScore(alignedSequences),
    conservedRegions: identifyConservedRegions(alignedSequences),
    method: params.method
  };
};

/**
 * Calculates a simple alignment score based on conservation
 */
const calculateAlignmentScore = (alignedSequences: Sequence[]): number => {
  if (alignedSequences.length === 0 || alignedSequences[0].content.length === 0) {
    return 0;
  }
  
  const seqLength = alignedSequences[0].content.length;
  let conservedCount = 0;
  let similarCount = 0;
  
  // For each position in the alignment
  for (let i = 0; i < seqLength; i++) {
    const positionChars = new Set<string>();
    
    // Collect all characters at this position
    for (const seq of alignedSequences) {
      if (i < seq.content.length) {
        positionChars.add(seq.content[i]);
      }
    }
    
    // If there's only one character (ignoring gaps), it's conserved
    if (positionChars.size === 1 && !positionChars.has('-')) {
      conservedCount++;
    }
    // If there are only a few characters, it's similar
    else if (positionChars.size <= 3 && !positionChars.has('-')) {
      similarCount++;
    }
  }
  
  // Return weighted score (conserved positions count more)
  return ((conservedCount * 1.0) + (similarCount * 0.5)) / seqLength * 100;
};

/**
 * Identifies conserved regions in the alignment
 */
const identifyConservedRegions = (alignedSequences: Sequence[]): { start: number, end: number }[] => {
  if (alignedSequences.length === 0 || alignedSequences[0].content.length === 0) {
    return [];
  }
  
  const seqLength = alignedSequences[0].content.length;
  const conservedPositions: boolean[] = [];
  
  // For each position in the alignment
  for (let i = 0; i < seqLength; i++) {
    const positionChars = new Set<string>();
    
    // Collect all characters at this position (excluding gaps)
    for (const seq of alignedSequences) {
      if (i < seq.content.length && seq.content[i] !== '-') {
        positionChars.add(seq.content[i]);
      }
    }
    
    // If there's only one character or two similar characters, it's conserved
    const isConserved = positionChars.size === 1 || 
      (positionChars.size === 2 && areAminoAcidsSimilar(Array.from(positionChars)));
    
    conservedPositions.push(isConserved);
  }
  
  // Find conserved regions (stretches of conserved positions)
  const regions: { start: number, end: number }[] = [];
  let inRegion = false;
  let regionStart = 0;
  
  // Set minimum conserved region length
  const MIN_REGION_LENGTH = 3;
  
  for (let i = 0; i < conservedPositions.length; i++) {
    if (conservedPositions[i] && !inRegion) {
      // Start of a new conserved region
      inRegion = true;
      regionStart = i;
    } else if (!conservedPositions[i] && inRegion) {
      // End of a conserved region
      inRegion = false;
      const regionLength = i - regionStart;
      if (regionLength >= MIN_REGION_LENGTH) {
        regions.push({ start: regionStart, end: i - 1 });
      }
    }
  }
  
  // Handle case where sequence ends with a conserved region
  if (inRegion) {
    const regionLength = conservedPositions.length - regionStart;
    if (regionLength >= MIN_REGION_LENGTH) {
      regions.push({ start: regionStart, end: conservedPositions.length - 1 });
    }
  }
  
  return regions;
};

/**
 * Determines if two amino acids are similar based on their properties
 */
const areAminoAcidsSimilar = (aminoAcids: string[]): boolean => {
  if (aminoAcids.length !== 2) return false;
  
  // Define groups of similar amino acids
  const similarGroups = [
    ['A', 'G', 'S', 'T'], // Small/polar
    ['I', 'L', 'M', 'V'], // Hydrophobic
    ['F', 'W', 'Y'],      // Aromatic
    ['N', 'Q', 'S', 'T'], // Polar
    ['H', 'K', 'R'],      // Positive charge
    ['D', 'E'],           // Negative charge
    ['S', 'T']            // Hydroxyl
  ];
  
  // Check if both amino acids are in the same similarity group
  return similarGroups.some(group => 
    group.includes(aminoAcids[0]) && group.includes(aminoAcids[1])
  );
};